# Generated by Django 3.0.8 on 2020-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.TextField(blank=True, default='items', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imagepath',
            field=models.CharField(default='#', max_length=120),
        ),
    ]
