# Generated by Django 3.0.8 on 2020-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200708_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagepath',
            field=models.ImageField(upload_to='documents/images'),
        ),
    ]
