# Generated by Django 3.0.8 on 2020-07-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200709_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Show this product in my inventory.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt',
            field=models.TextField(blank=True, default='items', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagepath',
            field=models.ImageField(default='', null=True, upload_to='documents/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per Unit'),
        ),
    ]
