# Generated by Django 3.0.8 on 2020-07-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200709_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagepath',
            field=models.ImageField(default=True, null=True, upload_to='documents/images', verbose_name='Image'),
        ),
    ]
