# Generated by Django 3.0.8 on 2020-07-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200719_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagepath',
            field=models.ImageField(default='', null=True, upload_to='documents/images', verbose_name='Image'),
        ),
    ]
