# Generated by Django 3.0.8 on 2020-07-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200721_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alt',
            field=models.TextField(blank=True, default='items', null=True, verbose_name='Alt Image Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagepath',
            field=models.ImageField(default='', null=True, upload_to='documents/images', verbose_name='Image'),
        ),
    ]
