# Generated by Django 3.0.8 on 2020-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200721_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alt',
            field=models.TextField(blank=True, default='items', max_length=120, null=True, verbose_name='Alt Image Text'),
        ),
    ]
